package com.alu4r.atcrowdfunding.manager.dao;

import com.alu4r.atcrowdfunding.bean.Cert;
import java.util.List;

public interface CertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int insert(Cert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    Cert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    List<Cert> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int updateByPrimaryKey(Cert record);
}