package com.alu4r.atcrowdfunding.manager.dao;

import com.alu4r.atcrowdfunding.bean.MemberCert;
import java.util.List;

public interface MemberCertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int insert(MemberCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    MemberCert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    List<MemberCert> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_cert
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int updateByPrimaryKey(MemberCert record);
}