package com.alu4r.atcrowdfunding.manager.dao;

import com.alu4r.atcrowdfunding.bean.MemberProjectFollow;
import java.util.List;

public interface MemberProjectFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int insert(MemberProjectFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    MemberProjectFollow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    List<MemberProjectFollow> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member_project_follow
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int updateByPrimaryKey(MemberProjectFollow record);
}