package com.alu4r.atcrowdfunding.manager.dao;

import com.alu4r.atcrowdfunding.bean.Param;
import java.util.List;

public interface ParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int insert(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    Param selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    List<Param> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int updateByPrimaryKey(Param record);
}