package com.alu4r.atcrowdfunding.manager.dao;

import com.alu4r.atcrowdfunding.bean.ProjectTag;
import java.util.List;

public interface ProjectTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int insert(ProjectTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    ProjectTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    List<ProjectTag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int updateByPrimaryKey(ProjectTag record);
}