package com.alu4r.atcrowdfunding.manager.dao;

import com.alu4r.atcrowdfunding.bean.ProjectType;
import java.util.List;

public interface ProjectTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int insert(ProjectType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    ProjectType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    List<ProjectType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_type
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int updateByPrimaryKey(ProjectType record);
}