package com.alu4r.atcrowdfunding.manager.dao;

import com.alu4r.atcrowdfunding.bean.Return;
import java.util.List;

public interface ReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int insert(Return record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    Return selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    List<Return> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_return
     *
     * @mbg.generated Mon Jul 15 16:17:09 CST 2019
     */
    int updateByPrimaryKey(Return record);
}